// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../math/matrix2d.dart';
import '../scene_graph/shape.dart';

// These functions are ignored because they are not marked as `pub`: `point_in_shape`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CanvasEngine>>
abstract class CanvasEngine implements RustOpaqueInterface {
  /// Create a new empty engine instance.
  static CanvasEngine create() =>
      RustLib.instance.api.crateApiEngineCanvasEngineCreate();

  /// Hit test: find all shape IDs at a point (in canvas coordinates).
  /// Returns IDs sorted by z-order (topmost first).
  List<String> hitTestPoint({required double x, required double y});

  /// Hit test: find all shape IDs overlapping a rectangle (for drag-select).
  List<String> hitTestRect(
      {required double x,
      required double y,
      required double w,
      required double h});

  /// Bulk-load all shapes (full sync). Replaces the entire scene.
  Future<void> loadAllShapes({required List<RenderShape> shapes});

  /// Get depth-first shape IDs in paint order.
  List<String> paintOrder();

  /// Query shape IDs visible within a viewport rectangle.
  List<String> queryVisible(
      {required double viewportMinX,
      required double viewportMinY,
      required double viewportMaxX,
      required double viewportMaxY});

  /// Get shape count.
  BigInt shapeCount();

  /// Sync a batch of shape changes from Dart → Rust.
  /// Called when CanvasBloc emits a new state.
  Future<void> syncShapes(
      {required List<RenderShape> added,
      required List<RenderShape> updated,
      required List<String> removed});
}
