import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:vio_core/vio_core.dart' hide StrokeCap, StrokeJoin;
import 'package:vio_ui_kit/vio_ui_kit.dart';

import '../../../../core/services/image_cache_service.dart';
import '../../../../rust/lib.dart';
import '../../../../rust/render/commands.dart';
import '../../models/selection_handle_metrics.dart';
import '../viewport_notifier.dart';
import 'shape_painter.dart';

/// Canvas painter that executes draw commands generated by the Rust engine.
///
/// This replaces [CanvasPainter]'s shape-rendering hot path with a flat
/// command list produced by `CanvasEngine.generateDrawCommands()`.
///
/// Selection outlines, hover highlights, drag overlays, and frame labels
/// remain in Dart for now — only the shape fill/stroke/shadow paint work
/// is driven by Rust.
///
/// **Viewport fast path:** The painter reads viewport state from
/// [viewportNotifier] which also serves as its `repaint` listenable.
/// During pan/zoom only the view matrix changes — draw commands are reused
/// as-is, no FFI call needed.
class RustCanvasPainter extends CustomPainter {
  RustCanvasPainter({
    required ViewportNotifier repaintNotifier,
    required this.drawCommands,
    required this.shapes,
    required this.shapesById,
    required this.viewportNotifier,
    required this.interactionNotifier,
    this.dragRect,
    this.dragOffset,
    this.selectedShapeIds = const [],
    this.hoveredShapeId,
    this.hoveredLayerId,
    this.editingTextShapeId,
  }) : super(repaint: repaintNotifier);

  // ---------------------------------------------------------------
  // Static caches — survive across painter instances to avoid expensive
  // re-creation of TextPainter / Path objects every frame.
  // ---------------------------------------------------------------

  /// TextPainter cache keyed by content + style parameters.
  /// Avoids expensive text layout computation on every frame.
  static final Map<_TextCacheKey, TextPainter> _textPainterCache = {};

  /// Parsed SVG Path cache keyed by the raw pathData string.
  /// Avoids regex-based path parsing on every frame.
  static final Map<String, Path?> _pathCache = {};

  /// Maximum entries in each cache before eviction.
  static const int _maxTextCacheSize = 512;
  static const int _maxPathCacheSize = 512;

  /// Pre-computed draw commands from the Rust engine.
  final List<DrawCommand> drawCommands;

  /// All shapes (for drag overlay, hover, selection — still Dart-driven).
  final List<Shape> shapes;

  /// Shape lookup map.
  final Map<String, Shape> shapesById;

  /// Viewport notifier — provides viewMatrix and zoom.
  final ViewportNotifier viewportNotifier;

  /// Interaction state — whether pan/zoom is in progress.
  final ValueNotifier<bool> interactionNotifier;

  /// Drag selection rect (canvas coords).
  final Rect? dragRect;

  /// Drag offset for moving shapes.
  final Offset? dragOffset;

  /// Selected shape IDs.
  final List<String> selectedShapeIds;

  /// Hovered shape ID on canvas.
  final String? hoveredShapeId;

  /// Hovered layer ID in layers panel.
  final String? hoveredLayerId;

  /// Text shape currently being edited by overlay.
  final String? editingTextShapeId;

  /// Read viewport state from the notifier — always current on each paint.
  Matrix2D get viewMatrix => viewportNotifier.viewMatrix;
  bool get simplifyForInteraction => interactionNotifier.value;

  double get _zoom {
    final z = viewMatrix.a.abs();
    return z <= 0 ? 1.0 : z;
  }

  @override
  void paint(Canvas canvas, Size size) {
    // Execute Rust-generated draw commands for shape rendering.
    _executeDrawCommands(canvas);

    // Drag overlay, hover/selection decorations remain in Dart.
    _paintDragOverlay(canvas, size);

    if (!simplifyForInteraction) {
      _paintHoverOutlines(canvas, size);
      _paintSelectionOutlines(canvas, size);
      _paintDragRect(canvas);
    }
  }

  // ---------------------------------------------------------------
  // Draw command executor
  // ---------------------------------------------------------------

  void _executeDrawCommands(Canvas canvas) {
    // Apply the current view matrix from the notifier — commands are in
    // world (canvas) coordinates so the Dart painter is responsible for
    // the camera transform. This allows cached commands to be replayed
    // with an updated view matrix during pan/zoom without FFI.
    final vm = viewMatrix;
    canvas.save();
    canvas.transform(Float64List.fromList([
      vm.a, vm.b, 0, 0, //
      vm.c, vm.d, 0, 0, //
      0, 0, 1, 0, //
      vm.e, vm.f, 0, 1, //
    ]),);

    for (final cmd in drawCommands) {
      switch (cmd) {
        case DrawCommand_PushTransform(:final matrix):
          canvas.save();
          canvas.transform(Float64List.fromList([
            matrix[0], matrix[1], 0, 0, //
            matrix[2], matrix[3], 0, 0, //
            0, 0, 1, 0, //
            matrix[4], matrix[5], 0, 1, //
          ]),);

        case DrawCommand_PopTransform():
          canvas.restore();

        case DrawCommand_Save():
          canvas.save();

        case DrawCommand_SaveLayer(:final bounds, :final opacity):
          final r = _toRect(bounds);
          canvas.saveLayer(
            r,
            Paint()..color = Color.fromARGB((opacity * 255).round(), 0, 0, 0),
          );

        case DrawCommand_Restore():
          canvas.restore();

        case DrawCommand_ClipRect(:final rect):
          canvas.clipRect(_toRect(rect));

        case DrawCommand_ClipRRect(:final rect, :final radii):
          canvas.clipRRect(_toRRect(rect, radii));

        case DrawCommand_ClipOval(:final rect):
          canvas.clipRect(_toRect(rect)); // close enough for ovals

        case DrawCommand_DrawRect(:final rect, :final color):
          canvas.drawRect(_toRect(rect), Paint()..color = _toColor(color));

        case DrawCommand_DrawRRect(:final rect, :final radii, :final color):
          canvas.drawRRect(
            _toRRect(rect, radii),
            Paint()..color = _toColor(color),
          );

        case DrawCommand_DrawRRectGradient(:final rect, :final radii, :final gradient):
          final r = _toRect(rect);
          final paint = Paint()..shader = _toShader(gradient, r);
          canvas.drawRRect(_toRRect(rect, radii), paint);

        case DrawCommand_DrawRRectStroke(
            :final rect,
            :final radii,
            :final color,
            :final strokeWidth,
            :final strokeAlignment,
          ):
          _drawStrokedRRect(canvas, rect, radii, color, strokeWidth, strokeAlignment);

        case DrawCommand_DrawOval(:final rect, :final color):
          canvas.drawOval(_toRect(rect), Paint()..color = _toColor(color));

        case DrawCommand_DrawOvalGradient(:final rect, :final gradient):
          final r = _toRect(rect);
          final paint = Paint()..shader = _toShader(gradient, r);
          canvas.drawOval(r, paint);

        case DrawCommand_DrawOvalStroke(:final rect, :final color, :final strokeWidth):
          final paint = Paint()
            ..color = _toColor(color)
            ..style = PaintingStyle.stroke
            ..strokeWidth = strokeWidth;
          canvas.drawOval(_toRect(rect), paint);

        case DrawCommand_DrawText(
            :final text,
            :final rect,
            :final fontSize,
            :final fontFamily,
            :final fontWeight,
            :final color,
            :final lineHeight,
            :final letterSpacing,
            :final textAlign,
          ):
          _drawText(canvas, text, rect, fontSize, fontFamily, fontWeight,
              color, lineHeight, letterSpacing, textAlign,);

        case DrawCommand_DrawImage(:final assetId, :final dstRect, :final filterQuality):
          _drawImage(canvas, assetId, dstRect, filterQuality);

        case DrawCommand_DrawShadow(
            :final pathType,
            :final rect,
            :final radii,
            :final color,
            :final blurSigma,
            :final offset,
            :final spread,
          ):
          _drawShadow(canvas, pathType, rect, radii, color, blurSigma, offset, spread);

        case DrawCommand_PushBlur(:final sigmaX, :final sigmaY, :final bounds):
          canvas.saveLayer(
            _toRect(bounds),
            Paint()
              ..imageFilter = ui.ImageFilter.blur(
                sigmaX: sigmaX,
                sigmaY: sigmaY,
              ),
          );

        case DrawCommand_PopBlur():
          canvas.restore();

        case DrawCommand_DrawPath(:final pathData, :final color, :final stroke):
          _drawPath(canvas, pathData, color, stroke);
      }
    }

    // Pop the view matrix pushed at the top.
    canvas.restore();
  }

  // ---------------------------------------------------------------
  // Conversion helpers
  // ---------------------------------------------------------------

  static Rect _toRect(F64Array4 r) =>
      Rect.fromLTWH(r[0], r[1], r[2], r[3]);

  static RRect _toRRect(F64Array4 r, F64Array4 radii) {
    final rect = Rect.fromLTWH(r[0], r[1], r[2], r[3]);
    return RRect.fromRectAndCorners(
      rect,
      topLeft: Radius.circular(radii[0]),
      topRight: Radius.circular(radii[1]),
      bottomRight: Radius.circular(radii[2]),
      bottomLeft: Radius.circular(radii[3]),
    );
  }

  static Color _toColor(int argb) => Color(argb);

  static ui.Shader _toShader(GradientData g, Rect bounds) {
    final colors = g.colors.map(Color.new).toList();
    final stops = g.stops.toList().cast<double>();
    // Gradient coordinates are relative to shape bounds (0..1 → pixels)
    final startX = bounds.left + g.start[0] * bounds.width;
    final startY = bounds.top + g.start[1] * bounds.height;
    final endX = bounds.left + g.end[0] * bounds.width;
    final endY = bounds.top + g.end[1] * bounds.height;

    if (g.gradientType == 1) {
      // Radial
      final radius = (Offset(endX, endY) - Offset(startX, startY)).distance;
      return ui.Gradient.radial(
        Offset(startX, startY),
        radius > 0 ? radius : 1.0,
        colors,
        stops,
      );
    }
    // Linear
    return ui.Gradient.linear(
      Offset(startX, startY),
      Offset(endX, endY),
      colors,
      stops,
    );
  }

  // ---------------------------------------------------------------
  // Stroke alignment handling
  // ---------------------------------------------------------------

  void _drawStrokedRRect(
    Canvas canvas,
    F64Array4 rect,
    F64Array4 radii,
    int color,
    double strokeWidth,
    int alignment,
  ) {
    final paint = Paint()
      ..color = _toColor(color)
      ..style = PaintingStyle.stroke;

    switch (alignment) {
      case 1: // Inside
        canvas.save();
        canvas.clipRRect(_toRRect(rect, radii));
        paint.strokeWidth = strokeWidth * 2;
        canvas.drawRRect(_toRRect(rect, radii), paint);
        canvas.restore();
      case 2: // Outside
        canvas.save();
        // Clip to everything *except* the shape (draw outside)
        canvas.clipRRect(_toRRect(rect, radii), doAntiAlias: false);
        // Invert — draw beyond the clip
        final bigRect = Rect.fromLTWH(
          rect[0] - strokeWidth * 4,
          rect[1] - strokeWidth * 4,
          rect[2] + strokeWidth * 8,
          rect[3] + strokeWidth * 8,
        );
        canvas.clipRect(bigRect, clipOp: ui.ClipOp.difference);
        // Re-clip negated
        canvas.clipRRect(
          _toRRect(rect, radii),
          doAntiAlias: false,
        );
        paint.strokeWidth = strokeWidth * 2;
        canvas.drawRRect(_toRRect(rect, radii), paint);
        canvas.restore();
      default: // Center
        paint.strokeWidth = strokeWidth;
        canvas.drawRRect(_toRRect(rect, radii), paint);
    }
  }

  // ---------------------------------------------------------------
  // Text rendering
  // ---------------------------------------------------------------

  void _drawText(
    Canvas canvas,
    String text,
    F64Array4 rect,
    double fontSize,
    String fontFamily,
    int fontWeight,
    int color,
    double lineHeight,
    double letterSpacing,
    int textAlign,
  ) {
    if (text.isEmpty) return;

    final width = rect[2] - rect[0];
    final height = rect[3] - rect[1];

    final ta = switch (textAlign) {
      1 => TextAlign.center,
      2 => TextAlign.right,
      3 => TextAlign.justify,
      _ => TextAlign.left,
    };

    final key = _TextCacheKey(
      text: text,
      fontSize: fontSize,
      fontFamily: fontFamily,
      fontWeight: fontWeight,
      lineHeight: lineHeight,
      letterSpacing: letterSpacing,
      textAlign: textAlign,
      maxWidth: width > 0 ? width : double.infinity,
      color: color,
    );

    var tp = _textPainterCache[key];
    if (tp == null) {
      // Evict oldest entries if cache is too large
      if (_textPainterCache.length >= _maxTextCacheSize) {
        final keysToRemove =
            _textPainterCache.keys.take(_maxTextCacheSize ~/ 4).toList();
        for (final k in keysToRemove) {
          _textPainterCache.remove(k)?.dispose();
        }
      }

      tp = TextPainter(
        text: TextSpan(
          text: text,
          style: TextStyle(
            color: _toColor(color),
            fontSize: fontSize,
            fontFamily: fontFamily,
            fontWeight:
                FontWeight.values[((fontWeight ~/ 100) - 1).clamp(0, 8)],
            height: lineHeight > 0 ? lineHeight : null,
            letterSpacing: letterSpacing != 0 ? letterSpacing : null,
          ),
        ),
        textAlign: ta,
        textDirection: TextDirection.ltr,
      )..layout(maxWidth: width > 0 ? width : double.infinity);

      _textPainterCache[key] = tp;
    }

    canvas.save();
    canvas.translate(rect[0], rect[1]);
    canvas.clipRect(Rect.fromLTWH(0, 0, width, height));
    tp.paint(canvas, Offset.zero);
    canvas.restore();
  }

  // ---------------------------------------------------------------
  // Image rendering
  // ---------------------------------------------------------------

  void _drawImage(
    Canvas canvas,
    String assetId,
    F64Array4 dstRect,
    int filterQuality,
  ) {
    final image = ImageCacheService.instance.get(assetId);
    if (image == null) {
      // Draw placeholder
      final r = _toRect(dstRect);
      final paint = Paint()..color = const Color(0xFF2A2A2A);
      canvas.drawRect(r, paint);
      return;
    }

    final srcRect = Rect.fromLTWH(
      0,
      0,
      image.width.toDouble(),
      image.height.toDouble(),
    );
    final dst = _toRect(dstRect);
    final fq = switch (filterQuality) {
      0 => FilterQuality.none,
      1 => FilterQuality.low,
      _ => FilterQuality.medium,
    };

    canvas.drawImageRect(image, srcRect, dst, Paint()..filterQuality = fq);
  }

  // ---------------------------------------------------------------
  // Shadow rendering
  // ---------------------------------------------------------------

  void _drawShadow(
    Canvas canvas,
    int pathType,
    F64Array4 rect,
    F64Array4 radii,
    int color,
    double blurSigma,
    F64Array2 offset,
    double spread,
  ) {
    if (pathType == 3) {
      // Inner shadow — complex compositing, delegate to Dart ShapePainter
      // approach: saveLayer + src-in blend. For now, simplified version.
      _drawInnerShadow(canvas, rect, color, blurSigma, offset, spread);
      return;
    }

    canvas.save();
    canvas.translate(offset[0], offset[1]);

    // Expand rect by spread
    final r = Rect.fromLTWH(
      rect[0] - spread,
      rect[1] - spread,
      rect[2] + spread * 2,
      rect[3] + spread * 2,
    );

    final paint = Paint()
      ..color = _toColor(color)
      ..maskFilter = blurSigma > 0 ? MaskFilter.blur(BlurStyle.normal, blurSigma) : null;

    switch (pathType) {
      case 1: // rrect
        final spreadRadii = F64Array4(Float64List.fromList(
          List.generate(4, (i) => (radii[i] + spread).clamp(0, double.infinity)),
        ),);
        final rrectRect = F64Array4(Float64List.fromList([r.left, r.top, r.width, r.height]));
        canvas.drawRRect(
          _toRRect(rrectRect, spreadRadii),
          paint,
        );
      case 2: // oval
        canvas.drawOval(r, paint);
      default: // rect
        canvas.drawRect(r, paint);
    }

    canvas.restore();
  }

  void _drawInnerShadow(
    Canvas canvas,
    F64Array4 rect,
    int color,
    double blurSigma,
    F64Array2 offset,
    double spread,
  ) {
    final r = _toRect(rect);
    // Save layer with the shape as the mask
    canvas.saveLayer(r.inflate(blurSigma * 2 + spread.abs()), Paint());

    // Fill shape with shadow colour
    canvas.drawRect(r, Paint()..color = _toColor(color));

    // Cut out an offset, shrunk copy using src-out
    final shrunkRect = r.deflate(spread);
    final offsetRect = shrunkRect.shift(Offset(offset[0], offset[1]));
    final erasePaint = Paint()
      ..blendMode = BlendMode.dstOut
      ..maskFilter =
          blurSigma > 0 ? MaskFilter.blur(BlurStyle.normal, blurSigma) : null;
    canvas.drawRect(offsetRect, erasePaint);

    // Clip to original shape
    canvas.restore();
  }

  // ---------------------------------------------------------------
  // Path rendering
  // ---------------------------------------------------------------

  void _drawPath(Canvas canvas, String pathData, int color, StrokeData? stroke) {
    // SVG path parsing — for now use Flutter's path builder
    // This is a placeholder; full SVG path parsing will be added in Phase 3
    if (stroke != null) {
      final paint = Paint()
        ..color = _toColor(stroke.color)
        ..style = PaintingStyle.stroke
        ..strokeWidth = stroke.width
        ..strokeCap = switch (stroke.cap) {
          1 => StrokeCap.round,
          2 => StrokeCap.square,
          _ => StrokeCap.butt,
        }
        ..strokeJoin = switch (stroke.join) {
          1 => StrokeJoin.round,
          2 => StrokeJoin.bevel,
          _ => StrokeJoin.miter,
        };
      // Path parsing deferred — stroke outline only
      if (color != 0) {
        // Has fill too
        final fillPaint = Paint()..color = _toColor(color);
        final path = _parseSvgPath(pathData);
        if (path != null) {
          canvas.drawPath(path, fillPaint);
          canvas.drawPath(path, paint);
        }
      } else {
        final path = _parseSvgPath(pathData);
        if (path != null) canvas.drawPath(path, paint);
      }
    } else if (color != 0) {
      final paint = Paint()..color = _toColor(color);
      final path = _parseSvgPath(pathData);
      if (path != null) canvas.drawPath(path, paint);
    }
  }

  /// Minimal SVG path parser — handles M, L, C, Q, Z commands.
  /// Results are cached by [pathData] to avoid regex parsing every frame.
  static Path? _parseSvgPath(String data) {
    if (data.isEmpty) return null;

    final cached = _pathCache[data];
    if (cached != null || _pathCache.containsKey(data)) return cached;

    // Evict oldest entries if cache is full
    if (_pathCache.length >= _maxPathCacheSize) {
      final keysToRemove = _pathCache.keys.take(_maxPathCacheSize ~/ 4).toList();
      for (final k in keysToRemove) {
        _pathCache.remove(k);
      }
    }

    final parsed = _parseSvgPathUncached(data);
    _pathCache[data] = parsed;
    return parsed;
  }

  static Path? _parseSvgPathUncached(String data) {
    try {
      final path = Path();
      final segments = RegExp('[MLCQZAHVSmlcqzahvs][^MLCQZAHVSmlcqzahvs]*')
          .allMatches(data);
      double cx = 0, cy = 0;

      for (final seg in segments) {
        final s = seg.group(0)!;
        final cmd = s[0];
        final nums = RegExp(r'-?[\d.]+')
            .allMatches(s.substring(1))
            .map((m) => double.parse(m.group(0)!))
            .toList();

        switch (cmd) {
          case 'M':
            if (nums.length >= 2) {
              path.moveTo(nums[0], nums[1]);
              cx = nums[0];
              cy = nums[1];
            }
          case 'm':
            if (nums.length >= 2) {
              cx += nums[0];
              cy += nums[1];
              path.moveTo(cx, cy);
            }
          case 'L':
            if (nums.length >= 2) {
              path.lineTo(nums[0], nums[1]);
              cx = nums[0];
              cy = nums[1];
            }
          case 'l':
            if (nums.length >= 2) {
              cx += nums[0];
              cy += nums[1];
              path.lineTo(cx, cy);
            }
          case 'H':
            if (nums.isNotEmpty) {
              cx = nums[0];
              path.lineTo(cx, cy);
            }
          case 'h':
            if (nums.isNotEmpty) {
              cx += nums[0];
              path.lineTo(cx, cy);
            }
          case 'V':
            if (nums.isNotEmpty) {
              cy = nums[0];
              path.lineTo(cx, cy);
            }
          case 'v':
            if (nums.isNotEmpty) {
              cy += nums[0];
              path.lineTo(cx, cy);
            }
          case 'C':
            if (nums.length >= 6) {
              path.cubicTo(nums[0], nums[1], nums[2], nums[3], nums[4], nums[5]);
              cx = nums[4];
              cy = nums[5];
            }
          case 'c':
            if (nums.length >= 6) {
              path.relativeCubicTo(
                  nums[0], nums[1], nums[2], nums[3], nums[4], nums[5],);
              cx += nums[4];
              cy += nums[5];
            }
          case 'Q':
            if (nums.length >= 4) {
              path.quadraticBezierTo(nums[0], nums[1], nums[2], nums[3]);
              cx = nums[2];
              cy = nums[3];
            }
          case 'q':
            if (nums.length >= 4) {
              path.relativeQuadraticBezierTo(
                  nums[0], nums[1], nums[2], nums[3],);
              cx += nums[2];
              cy += nums[3];
            }
          case 'Z':
          case 'z':
            path.close();
        }
      }
      return path;
    } catch (_) {
      return null;
    }
  }

  // ---------------------------------------------------------------
  // Drag overlay (same logic as CanvasPainter)
  // ---------------------------------------------------------------

  void _paintDragOverlay(Canvas canvas, Size size) {
    if (dragOffset == null || selectedShapeIds.isEmpty) return;

    final selectedIdSet = selectedShapeIds.toSet();
    final childrenByContainer = _buildChildrenMap();

    // Collect dragged shapes + descendants
    final dragIds = <String>{...selectedIdSet};
    void addDescendants(String id) {
      final children = childrenByContainer[id];
      if (children == null) return;
      for (final child in children) {
        if (dragIds.add(child.id)) addDescendants(child.id);
      }
    }
    for (final id in selectedIdSet) {
      final shape = shapesById[id];
      if (shape is GroupShape || shape is FrameShape) addDescendants(id);
    }

    // Apply view transform
    canvas.save();
    canvas.transform(Float64List.fromList([
      viewMatrix.a, viewMatrix.b, 0, 0,
      viewMatrix.c, viewMatrix.d, 0, 0,
      0, 0, 1, 0,
      viewMatrix.e, viewMatrix.f, 0, 1,
    ]),);

    for (final shape in shapes) {
      if (!dragIds.contains(shape.id)) continue;

      canvas.save();
      canvas.translate(dragOffset!.dx, dragOffset!.dy);

      // Apply frame clipping
      final frameId = shape.frameId;
      final frame = frameId == null ? null : shapesById[frameId];
      if (frame is FrameShape && frame.clipContent) {
        // If frame is also dragging, translate the clip with it
        if (dragIds.contains(frameId)) {
          canvas.clipRect(Rect.fromLTWH(
            frame.x, frame.y, frame.frameWidth, frame.frameHeight,
          ),);
        } else {
          canvas.restore();
          canvas.save();
          canvas.clipRect(Rect.fromLTWH(
            frame.x, frame.y, frame.frameWidth, frame.frameHeight,
          ),);
          canvas.translate(dragOffset!.dx, dragOffset!.dy);
        }
      }

      if (shape is! TextShape || shape.id != editingTextShapeId) {
        ShapePainter.paintShape(canvas, shape,
            simplifyForInteraction: simplifyForInteraction,);
      }
      canvas.restore();
    }

    canvas.restore();
  }

  // ---------------------------------------------------------------
  // Hover outlines
  // ---------------------------------------------------------------

  void _paintHoverOutlines(Canvas canvas, Size size) {
    final hoverIds = <String>{};
    if (hoveredShapeId != null) hoverIds.add(hoveredShapeId!);
    if (hoveredLayerId != null) hoverIds.add(hoveredLayerId!);

    final selectedSet = selectedShapeIds.toSet();
    hoverIds.removeAll(selectedSet);
    if (hoverIds.isEmpty) return;

    final strokeWidth = SelectionHandleMetrics.toCanvasUnits(
      screenPx: 1.5,
      zoom: _zoom,
    );

    canvas.save();
    canvas.transform(Float64List.fromList([
      viewMatrix.a, viewMatrix.b, 0, 0,
      viewMatrix.c, viewMatrix.d, 0, 0,
      0, 0, 1, 0,
      viewMatrix.e, viewMatrix.f, 0, 1,
    ]),);

    final paint = Paint()
      ..color = VioColors.primary.withValues(alpha: 0.5)
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth;

    for (final id in hoverIds) {
      final shape = shapesById[id];
      if (shape == null || shape.hidden) continue;
      final r = Rect.fromLTWH(shape.x, shape.y, shape.width, shape.height);
      canvas.drawRect(r, paint);
    }

    canvas.restore();
  }

  // ---------------------------------------------------------------
  // Selection outlines
  // ---------------------------------------------------------------

  void _paintSelectionOutlines(Canvas canvas, Size size) {
    if (selectedShapeIds.isEmpty) return;

    final strokeWidth = SelectionHandleMetrics.toCanvasUnits(
      screenPx: 1.5,
      zoom: _zoom,
    );

    canvas.save();
    canvas.transform(Float64List.fromList([
      viewMatrix.a, viewMatrix.b, 0, 0,
      viewMatrix.c, viewMatrix.d, 0, 0,
      0, 0, 1, 0,
      viewMatrix.e, viewMatrix.f, 0, 1,
    ]),);

    final paint = Paint()
      ..color = VioColors.primary
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth;

    for (final id in selectedShapeIds) {
      final shape = shapesById[id];
      if (shape == null || shape.hidden) continue;
      final offset = dragOffset ?? Offset.zero;
      final r = Rect.fromLTWH(
        shape.x + offset.dx,
        shape.y + offset.dy,
        shape.width,
        shape.height,
      );
      canvas.drawRect(r, paint);
    }

    canvas.restore();
  }

  // ---------------------------------------------------------------
  // Drag rect (marquee selection box)
  // ---------------------------------------------------------------

  void _paintDragRect(Canvas canvas) {
    if (dragRect == null) return;

    canvas.save();
    canvas.transform(Float64List.fromList([
      viewMatrix.a, viewMatrix.b, 0, 0,
      viewMatrix.c, viewMatrix.d, 0, 0,
      0, 0, 1, 0,
      viewMatrix.e, viewMatrix.f, 0, 1,
    ]),);

    final fill = Paint()
      ..color = VioColors.primary.withValues(alpha: 0.1)
      ..style = PaintingStyle.fill;
    final stroke = Paint()
      ..color = VioColors.primary
      ..style = PaintingStyle.stroke
      ..strokeWidth = SelectionHandleMetrics.toCanvasUnits(
        screenPx: 1.0,
        zoom: _zoom,
      );

    canvas.drawRect(dragRect!, fill);
    canvas.drawRect(dragRect!, stroke);

    canvas.restore();
  }

  // ---------------------------------------------------------------
  // Utility
  // ---------------------------------------------------------------

  Map<String, List<Shape>> _buildChildrenMap() {
    final map = <String, List<Shape>>{};
    for (final shape in shapes) {
      final parentId = shape.parentId;
      final frameId = shape.frameId;
      if (parentId != null && shapesById[parentId] is GroupShape) {
        map.putIfAbsent(parentId, () => []).add(shape);
      } else if (frameId != null && shapesById[frameId] is FrameShape) {
        map.putIfAbsent(frameId, () => []).add(shape);
      }
    }
    return map;
  }

  @override
  bool shouldRepaint(covariant RustCanvasPainter oldDelegate) {
    // The ViewportNotifier (repaint listenable) handles viewport-only changes.
    // Only return true here when non-viewport state changed (commands, shapes,
    // selection, hover, drag).
    return !identical(drawCommands, oldDelegate.drawCommands) ||
        !identical(shapes, oldDelegate.shapes) ||
        !identical(shapesById, oldDelegate.shapesById) ||
        selectedShapeIds != oldDelegate.selectedShapeIds ||
        hoveredShapeId != oldDelegate.hoveredShapeId ||
        hoveredLayerId != oldDelegate.hoveredLayerId ||
        editingTextShapeId != oldDelegate.editingTextShapeId ||
        dragRect != oldDelegate.dragRect ||
        dragOffset != oldDelegate.dragOffset;
  }
}

/// Cache key for [TextPainter] instances.
class _TextCacheKey {
  const _TextCacheKey({
    required this.text,
    required this.fontSize,
    required this.fontFamily,
    required this.fontWeight,
    required this.lineHeight,
    required this.letterSpacing,
    required this.textAlign,
    required this.maxWidth,
    required this.color,
  });

  final String text;
  final double fontSize;
  final String fontFamily;
  final int fontWeight;
  final double lineHeight;
  final double letterSpacing;
  final int textAlign;
  final double maxWidth;
  final int color;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is _TextCacheKey &&
          text == other.text &&
          fontSize == other.fontSize &&
          fontFamily == other.fontFamily &&
          fontWeight == other.fontWeight &&
          lineHeight == other.lineHeight &&
          letterSpacing == other.letterSpacing &&
          textAlign == other.textAlign &&
          maxWidth == other.maxWidth &&
          color == other.color;

  @override
  int get hashCode => Object.hash(
        text,
        fontSize,
        fontFamily,
        fontWeight,
        lineHeight,
        letterSpacing,
        textAlign,
        maxWidth,
        color,
      );
}
