/// Gradient data for draw commands.
#[derive(Debug, Clone, PartialEq)]
pub struct GradientData {
    /// 0 = linear, 1 = radial
    pub gradient_type: u8,
    pub colors: Vec<u32>,
    pub stops: Vec<f64>,
    pub start: [f64; 2],
    pub end: [f64; 2],
}

/// Stroke data for path draw commands.
#[derive(Debug, Clone, PartialEq)]
pub struct StrokeData {
    pub width: f64,
    pub color: u32,
    /// 0 = butt, 1 = round, 2 = square
    pub cap: u8,
    /// 0 = miter, 1 = round, 2 = bevel
    pub join: u8,
}

/// A flat, serializable draw instruction for Flutter's Canvas API.
///
/// Generated by the Rust render pipeline and executed by Dart's
/// `RustCanvasPainter`. Each variant maps to one or two Canvas calls.
#[derive(Debug, Clone, PartialEq)]
pub enum DrawCommand {
    /// Push a 2D affine transform matrix [a, b, c, d, e, f].
    PushTransform { matrix: [f64; 6] },
    /// Pop the last pushed transform.
    PopTransform,
    /// Save canvas state.
    Save,
    /// Save canvas state with a layer (for opacity, effects).
    SaveLayer {
        bounds: [f64; 4],
        opacity: f64,
    },
    /// Restore canvas state.
    Restore,
    /// Clip to a rectangle [x, y, w, h].
    ClipRect { rect: [f64; 4] },
    /// Clip to a rounded rectangle.
    ClipRRect {
        rect: [f64; 4],
        radii: [f64; 4],
    },
    /// Clip to an oval.
    ClipOval { rect: [f64; 4] },
    /// Draw a filled rectangle.
    DrawRect {
        rect: [f64; 4],
        color: u32,
    },
    /// Draw a filled rounded rectangle.
    DrawRRect {
        rect: [f64; 4],
        radii: [f64; 4],
        color: u32,
    },
    /// Draw a rounded rectangle with gradient fill.
    DrawRRectGradient {
        rect: [f64; 4],
        radii: [f64; 4],
        gradient: GradientData,
    },
    /// Draw a stroked rounded rectangle.
    DrawRRectStroke {
        rect: [f64; 4],
        radii: [f64; 4],
        color: u32,
        stroke_width: f64,
        /// 0 = center, 1 = inside, 2 = outside
        stroke_alignment: u8,
    },
    /// Draw a filled oval.
    DrawOval {
        rect: [f64; 4],
        color: u32,
    },
    /// Draw an oval with gradient fill.
    DrawOvalGradient {
        rect: [f64; 4],
        gradient: GradientData,
    },
    /// Draw a stroked oval.
    DrawOvalStroke {
        rect: [f64; 4],
        color: u32,
        stroke_width: f64,
    },
    /// Draw text at a position.
    DrawText {
        text: String,
        rect: [f64; 4],
        font_size: f64,
        font_family: String,
        font_weight: u16,
        color: u32,
        line_height: f64,
        letter_spacing: f64,
        text_align: u8,
    },
    /// Draw a cached image by asset ID.
    DrawImage {
        asset_id: String,
        dst_rect: [f64; 4],
        /// 0 = none, 1 = low, 2 = medium
        filter_quality: u8,
    },
    /// Draw a drop shadow.
    DrawShadow {
        /// 0 = rect, 1 = rrect, 2 = oval
        path_type: u8,
        rect: [f64; 4],
        radii: [f64; 4],
        color: u32,
        blur_sigma: f64,
        offset: [f64; 2],
        spread: f64,
    },
    /// Push a blur filter (saveLayer + ImageFilter.blur).
    PushBlur {
        sigma_x: f64,
        sigma_y: f64,
        bounds: [f64; 4],
    },
    /// Pop blur filter (restore).
    PopBlur,
    /// Draw an SVG path string with fill and/or stroke.
    DrawPath {
        path_data: String,
        color: u32,
        stroke: Option<StrokeData>,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn draw_command_clone() {
        let cmd = DrawCommand::DrawRRect {
            rect: [0.0, 0.0, 100.0, 50.0],
            radii: [5.0, 5.0, 5.0, 5.0],
            color: 0xFF0000FF,
        };
        let cloned = cmd.clone();
        assert_eq!(cmd, cloned);
    }

    #[test]
    fn gradient_data_construction() {
        let g = GradientData {
            gradient_type: 0,
            colors: vec![0xFF000000, 0xFFFFFFFF],
            stops: vec![0.0, 1.0],
            start: [0.0, 0.0],
            end: [100.0, 0.0],
        };
        assert_eq!(g.colors.len(), 2);
        assert_eq!(g.stops.len(), 2);
    }
}
