// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'commands.freezed.dart';

@freezed
sealed class DrawCommand with _$DrawCommand {
  const DrawCommand._();

  /// Push a 2D affine transform matrix [a, b, c, d, e, f].
  const factory DrawCommand.pushTransform({
    required F64Array6 matrix,
  }) = DrawCommand_PushTransform;

  /// Pop the last pushed transform.
  const factory DrawCommand.popTransform() = DrawCommand_PopTransform;

  /// Save canvas state.
  const factory DrawCommand.save() = DrawCommand_Save;

  /// Save canvas state with a layer (for opacity, effects).
  const factory DrawCommand.saveLayer({
    required F64Array4 bounds,
    required double opacity,
  }) = DrawCommand_SaveLayer;

  /// Restore canvas state.
  const factory DrawCommand.restore() = DrawCommand_Restore;

  /// Clip to a rectangle [x, y, w, h].
  const factory DrawCommand.clipRect({
    required F64Array4 rect,
  }) = DrawCommand_ClipRect;

  /// Clip to a rounded rectangle.
  const factory DrawCommand.clipRRect({
    required F64Array4 rect,
    required F64Array4 radii,
  }) = DrawCommand_ClipRRect;

  /// Clip to an oval.
  const factory DrawCommand.clipOval({
    required F64Array4 rect,
  }) = DrawCommand_ClipOval;

  /// Draw a filled rectangle.
  const factory DrawCommand.drawRect({
    required F64Array4 rect,
    required int color,
  }) = DrawCommand_DrawRect;

  /// Draw a filled rounded rectangle.
  const factory DrawCommand.drawRRect({
    required F64Array4 rect,
    required F64Array4 radii,
    required int color,
  }) = DrawCommand_DrawRRect;

  /// Draw a rounded rectangle with gradient fill.
  const factory DrawCommand.drawRRectGradient({
    required F64Array4 rect,
    required F64Array4 radii,
    required GradientData gradient,
  }) = DrawCommand_DrawRRectGradient;

  /// Draw a stroked rounded rectangle.
  const factory DrawCommand.drawRRectStroke({
    required F64Array4 rect,
    required F64Array4 radii,
    required int color,
    required double strokeWidth,

    /// 0 = center, 1 = inside, 2 = outside
    required int strokeAlignment,
  }) = DrawCommand_DrawRRectStroke;

  /// Draw a filled oval.
  const factory DrawCommand.drawOval({
    required F64Array4 rect,
    required int color,
  }) = DrawCommand_DrawOval;

  /// Draw an oval with gradient fill.
  const factory DrawCommand.drawOvalGradient({
    required F64Array4 rect,
    required GradientData gradient,
  }) = DrawCommand_DrawOvalGradient;

  /// Draw a stroked oval.
  const factory DrawCommand.drawOvalStroke({
    required F64Array4 rect,
    required int color,
    required double strokeWidth,
  }) = DrawCommand_DrawOvalStroke;

  /// Draw text at a position.
  const factory DrawCommand.drawText({
    required String text,
    required F64Array4 rect,
    required double fontSize,
    required String fontFamily,
    required int fontWeight,
    required int color,
    required double lineHeight,
    required double letterSpacing,
    required int textAlign,
  }) = DrawCommand_DrawText;

  /// Draw a cached image by asset ID.
  const factory DrawCommand.drawImage({
    required String assetId,
    required F64Array4 dstRect,

    /// 0 = none, 1 = low, 2 = medium
    required int filterQuality,
  }) = DrawCommand_DrawImage;

  /// Draw a drop shadow.
  const factory DrawCommand.drawShadow({
    /// 0 = rect, 1 = rrect, 2 = oval
    required int pathType,
    required F64Array4 rect,
    required F64Array4 radii,
    required int color,
    required double blurSigma,
    required F64Array2 offset,
    required double spread,
  }) = DrawCommand_DrawShadow;

  /// Push a blur filter (saveLayer + ImageFilter.blur).
  const factory DrawCommand.pushBlur({
    required double sigmaX,
    required double sigmaY,
    required F64Array4 bounds,
  }) = DrawCommand_PushBlur;

  /// Pop blur filter (restore).
  const factory DrawCommand.popBlur() = DrawCommand_PopBlur;

  /// Draw an SVG path string with fill and/or stroke.
  const factory DrawCommand.drawPath({
    required String pathData,
    required int color,
    StrokeData? stroke,
  }) = DrawCommand_DrawPath;

  /// Marks the beginning of a shape's commands (used for filtering by ID).
  const factory DrawCommand.beginShape({
    required String id,
  }) = DrawCommand_BeginShape;

  /// Marks the end of a shape's commands.
  const factory DrawCommand.endShape() = DrawCommand_EndShape;
}

/// Gradient data for draw commands.
class GradientData {
  /// 0 = linear, 1 = radial
  final int gradientType;
  final Uint32List colors;
  final Float64List stops;
  final F64Array2 start;
  final F64Array2 end;

  const GradientData({
    required this.gradientType,
    required this.colors,
    required this.stops,
    required this.start,
    required this.end,
  });

  @override
  int get hashCode =>
      gradientType.hashCode ^
      colors.hashCode ^
      stops.hashCode ^
      start.hashCode ^
      end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GradientData &&
          runtimeType == other.runtimeType &&
          gradientType == other.gradientType &&
          colors == other.colors &&
          stops == other.stops &&
          start == other.start &&
          end == other.end;
}

/// Stroke data for path draw commands.
class StrokeData {
  final double width;
  final int color;

  /// 0 = butt, 1 = round, 2 = square
  final int cap;

  /// 0 = miter, 1 = round, 2 = bevel
  final int join;

  const StrokeData({
    required this.width,
    required this.color,
    required this.cap,
    required this.join,
  });

  @override
  int get hashCode =>
      width.hashCode ^ color.hashCode ^ cap.hashCode ^ join.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrokeData &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          color == other.color &&
          cap == other.cap &&
          join == other.join;
}
