// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'api/engine.dart';
import 'api/simple.dart';
import 'frb_generated.dart';
import 'math/matrix2d.dart';
import 'scene_graph/shape.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_CanvasEnginePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEnginePtr;

  @protected
  CanvasEngine
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw);

  @protected
  CanvasEngine
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw);

  @protected
  CanvasEngine
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw);

  @protected
  CanvasEngine
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BlurType dco_decode_blur_type(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BoolOp dco_decode_bool_op(dynamic raw);

  @protected
  ShapeBlur dco_decode_box_autoadd_shape_blur(dynamic raw);

  @protected
  ShapeGradient dco_decode_box_autoadd_shape_gradient(dynamic raw);

  @protected
  ShapeShadow dco_decode_box_autoadd_shape_shadow(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GradientStop dco_decode_gradient_stop(dynamic raw);

  @protected
  GradientType dco_decode_gradient_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<GradientStop> dco_decode_list_gradient_stop(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RenderShape> dco_decode_list_render_shape(dynamic raw);

  @protected
  List<ShapeFill> dco_decode_list_shape_fill(dynamic raw);

  @protected
  List<ShapeStroke> dco_decode_list_shape_stroke(dynamic raw);

  @protected
  Matrix2D dco_decode_matrix_2_d(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ShapeBlur? dco_decode_opt_box_autoadd_shape_blur(dynamic raw);

  @protected
  ShapeGradient? dco_decode_opt_box_autoadd_shape_gradient(dynamic raw);

  @protected
  ShapeShadow? dco_decode_opt_box_autoadd_shape_shadow(dynamic raw);

  @protected
  RenderShape dco_decode_render_shape(dynamic raw);

  @protected
  ShadowStyle dco_decode_shadow_style(dynamic raw);

  @protected
  ShapeBlur dco_decode_shape_blur(dynamic raw);

  @protected
  ShapeFill dco_decode_shape_fill(dynamic raw);

  @protected
  ShapeGeometry dco_decode_shape_geometry(dynamic raw);

  @protected
  ShapeGradient dco_decode_shape_gradient(dynamic raw);

  @protected
  ShapeShadow dco_decode_shape_shadow(dynamic raw);

  @protected
  ShapeStroke dco_decode_shape_stroke(dynamic raw);

  @protected
  ShapeType dco_decode_shape_type(dynamic raw);

  @protected
  StrokeAlignment dco_decode_stroke_alignment(dynamic raw);

  @protected
  StrokeCap dco_decode_stroke_cap(dynamic raw);

  @protected
  StrokeJoin dco_decode_stroke_join(dynamic raw);

  @protected
  TextAlign dco_decode_text_align(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  CanvasEngine
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer);

  @protected
  CanvasEngine
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer);

  @protected
  CanvasEngine
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer);

  @protected
  CanvasEngine
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BlurType sse_decode_blur_type(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BoolOp sse_decode_bool_op(SseDeserializer deserializer);

  @protected
  ShapeBlur sse_decode_box_autoadd_shape_blur(SseDeserializer deserializer);

  @protected
  ShapeGradient sse_decode_box_autoadd_shape_gradient(
      SseDeserializer deserializer);

  @protected
  ShapeShadow sse_decode_box_autoadd_shape_shadow(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GradientStop sse_decode_gradient_stop(SseDeserializer deserializer);

  @protected
  GradientType sse_decode_gradient_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<GradientStop> sse_decode_list_gradient_stop(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RenderShape> sse_decode_list_render_shape(SseDeserializer deserializer);

  @protected
  List<ShapeFill> sse_decode_list_shape_fill(SseDeserializer deserializer);

  @protected
  List<ShapeStroke> sse_decode_list_shape_stroke(SseDeserializer deserializer);

  @protected
  Matrix2D sse_decode_matrix_2_d(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ShapeBlur? sse_decode_opt_box_autoadd_shape_blur(
      SseDeserializer deserializer);

  @protected
  ShapeGradient? sse_decode_opt_box_autoadd_shape_gradient(
      SseDeserializer deserializer);

  @protected
  ShapeShadow? sse_decode_opt_box_autoadd_shape_shadow(
      SseDeserializer deserializer);

  @protected
  RenderShape sse_decode_render_shape(SseDeserializer deserializer);

  @protected
  ShadowStyle sse_decode_shadow_style(SseDeserializer deserializer);

  @protected
  ShapeBlur sse_decode_shape_blur(SseDeserializer deserializer);

  @protected
  ShapeFill sse_decode_shape_fill(SseDeserializer deserializer);

  @protected
  ShapeGeometry sse_decode_shape_geometry(SseDeserializer deserializer);

  @protected
  ShapeGradient sse_decode_shape_gradient(SseDeserializer deserializer);

  @protected
  ShapeShadow sse_decode_shape_shadow(SseDeserializer deserializer);

  @protected
  ShapeStroke sse_decode_shape_stroke(SseDeserializer deserializer);

  @protected
  ShapeType sse_decode_shape_type(SseDeserializer deserializer);

  @protected
  StrokeAlignment sse_decode_stroke_alignment(SseDeserializer deserializer);

  @protected
  StrokeCap sse_decode_stroke_cap(SseDeserializer deserializer);

  @protected
  StrokeJoin sse_decode_stroke_join(SseDeserializer deserializer);

  @protected
  TextAlign sse_decode_text_align(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_blur_type(BlurType self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bool_op(BoolOp self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_shape_blur(
      ShapeBlur self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_shape_gradient(
      ShapeGradient self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_shape_shadow(
      ShapeShadow self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_gradient_stop(GradientStop self, SseSerializer serializer);

  @protected
  void sse_encode_gradient_type(GradientType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_gradient_stop(
      List<GradientStop> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_render_shape(
      List<RenderShape> self, SseSerializer serializer);

  @protected
  void sse_encode_list_shape_fill(
      List<ShapeFill> self, SseSerializer serializer);

  @protected
  void sse_encode_list_shape_stroke(
      List<ShapeStroke> self, SseSerializer serializer);

  @protected
  void sse_encode_matrix_2_d(Matrix2D self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_shape_blur(
      ShapeBlur? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_shape_gradient(
      ShapeGradient? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_shape_shadow(
      ShapeShadow? self, SseSerializer serializer);

  @protected
  void sse_encode_render_shape(RenderShape self, SseSerializer serializer);

  @protected
  void sse_encode_shadow_style(ShadowStyle self, SseSerializer serializer);

  @protected
  void sse_encode_shape_blur(ShapeBlur self, SseSerializer serializer);

  @protected
  void sse_encode_shape_fill(ShapeFill self, SseSerializer serializer);

  @protected
  void sse_encode_shape_geometry(ShapeGeometry self, SseSerializer serializer);

  @protected
  void sse_encode_shape_gradient(ShapeGradient self, SseSerializer serializer);

  @protected
  void sse_encode_shape_shadow(ShapeShadow self, SseSerializer serializer);

  @protected
  void sse_encode_shape_stroke(ShapeStroke self, SseSerializer serializer);

  @protected
  void sse_encode_shape_type(ShapeType self, SseSerializer serializer);

  @protected
  void sse_encode_stroke_alignment(
      StrokeAlignment self, SseSerializer serializer);

  @protected
  void sse_encode_stroke_cap(StrokeCap self, SseSerializer serializer);

  @protected
  void sse_encode_stroke_join(StrokeJoin self, SseSerializer serializer);

  @protected
  void sse_encode_text_align(TextAlign self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_vio_client_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_vio_client_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
