// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/engine.dart';
import 'api/simple.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'math/matrix2d.dart';
import 'scene_graph/shape.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1150966451;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_vio_client',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  CanvasEngine crateApiEngineCanvasEngineCreate();

  List<String> crateApiEngineCanvasEngineHitTestPoint(
      {required CanvasEngine that, required double x, required double y});

  List<String> crateApiEngineCanvasEngineHitTestRect(
      {required CanvasEngine that,
      required double x,
      required double y,
      required double w,
      required double h});

  Future<void> crateApiEngineCanvasEngineLoadAllShapes(
      {required CanvasEngine that, required List<RenderShape> shapes});

  List<String> crateApiEngineCanvasEnginePaintOrder(
      {required CanvasEngine that});

  List<String> crateApiEngineCanvasEngineQueryVisible(
      {required CanvasEngine that,
      required double viewportMinX,
      required double viewportMinY,
      required double viewportMaxX,
      required double viewportMaxY});

  BigInt crateApiEngineCanvasEngineShapeCount({required CanvasEngine that});

  Future<void> crateApiEngineCanvasEngineSyncShapes(
      {required CanvasEngine that,
      required List<RenderShape> added,
      required List<RenderShape> updated,
      required List<String> removed});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CanvasEngine;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CanvasEngine;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CanvasEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  CanvasEngine crateApiEngineCanvasEngineCreate() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEngineCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEngineCreateConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_create',
        argNames: [],
      );

  @override
  List<String> crateApiEngineCanvasEngineHitTestPoint(
      {required CanvasEngine that, required double x, required double y}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
              that, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEngineHitTestPointConstMeta,
        argValues: [that, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEngineHitTestPointConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_hit_test_point',
        argNames: ['that', 'x', 'y'],
      );

  @override
  List<String> crateApiEngineCanvasEngineHitTestRect(
      {required CanvasEngine that,
      required double x,
      required double y,
      required double w,
      required double h}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
              that, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_f_64(w, serializer);
          sse_encode_f_64(h, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEngineHitTestRectConstMeta,
        argValues: [that, x, y, w, h],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEngineHitTestRectConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_hit_test_rect',
        argNames: ['that', 'x', 'y', 'w', 'h'],
      );

  @override
  Future<void> crateApiEngineCanvasEngineLoadAllShapes(
      {required CanvasEngine that, required List<RenderShape> shapes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
              that, serializer);
          sse_encode_list_render_shape(shapes, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 4, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEngineLoadAllShapesConstMeta,
        argValues: [that, shapes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEngineLoadAllShapesConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_load_all_shapes',
        argNames: ['that', 'shapes'],
      );

  @override
  List<String> crateApiEngineCanvasEnginePaintOrder(
      {required CanvasEngine that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
              that, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEnginePaintOrderConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEnginePaintOrderConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_paint_order',
        argNames: ['that'],
      );

  @override
  List<String> crateApiEngineCanvasEngineQueryVisible(
      {required CanvasEngine that,
      required double viewportMinX,
      required double viewportMinY,
      required double viewportMaxX,
      required double viewportMaxY}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
              that, serializer);
          sse_encode_f_64(viewportMinX, serializer);
          sse_encode_f_64(viewportMinY, serializer);
          sse_encode_f_64(viewportMaxX, serializer);
          sse_encode_f_64(viewportMaxY, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEngineQueryVisibleConstMeta,
        argValues: [
          that,
          viewportMinX,
          viewportMinY,
          viewportMaxX,
          viewportMaxY
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEngineQueryVisibleConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_query_visible',
        argNames: [
          'that',
          'viewportMinX',
          'viewportMinY',
          'viewportMaxX',
          'viewportMaxY'
        ],
      );

  @override
  BigInt crateApiEngineCanvasEngineShapeCount({required CanvasEngine that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
              that, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEngineShapeCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEngineShapeCountConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_shape_count',
        argNames: ['that'],
      );

  @override
  Future<void> crateApiEngineCanvasEngineSyncShapes(
      {required CanvasEngine that,
      required List<RenderShape> added,
      required List<RenderShape> updated,
      required List<String> removed}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
              that, serializer);
          sse_encode_list_render_shape(added, serializer);
          sse_encode_list_render_shape(updated, serializer);
          sse_encode_list_String(removed, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 8, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineCanvasEngineSyncShapesConstMeta,
        argValues: [that, added, updated, removed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineCanvasEngineSyncShapesConstMeta =>
      const TaskConstMeta(
        debugName: 'CanvasEngine_sync_shapes',
        argNames: ['that', 'added', 'updated', 'removed'],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: 'greet',
        argNames: ['name'],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer,
              funcId: 10, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: 'init_app',
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_CanvasEngine => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_CanvasEngine => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine;

  @protected
  CanvasEngine
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CanvasEngine
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CanvasEngine
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CanvasEngine
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlurType dco_decode_blur_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BlurType.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BoolOp dco_decode_bool_op(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BoolOp.values[raw as int];
  }

  @protected
  ShapeBlur dco_decode_box_autoadd_shape_blur(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_shape_blur(raw);
  }

  @protected
  ShapeGradient dco_decode_box_autoadd_shape_gradient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_shape_gradient(raw);
  }

  @protected
  ShapeShadow dco_decode_box_autoadd_shape_shadow(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_shape_shadow(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GradientStop dco_decode_gradient_stop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GradientStop(
      offset: dco_decode_f_64(arr[0]),
      color: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  GradientType dco_decode_gradient_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GradientType.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<GradientStop> dco_decode_list_gradient_stop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_gradient_stop).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RenderShape> dco_decode_list_render_shape(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_render_shape).toList();
  }

  @protected
  List<ShapeFill> dco_decode_list_shape_fill(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_shape_fill).toList();
  }

  @protected
  List<ShapeStroke> dco_decode_list_shape_stroke(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_shape_stroke).toList();
  }

  @protected
  Matrix2D dco_decode_matrix_2_d(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Matrix2D(
      a: dco_decode_f_64(arr[0]),
      b: dco_decode_f_64(arr[1]),
      c: dco_decode_f_64(arr[2]),
      d: dco_decode_f_64(arr[3]),
      e: dco_decode_f_64(arr[4]),
      f: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ShapeBlur? dco_decode_opt_box_autoadd_shape_blur(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_shape_blur(raw);
  }

  @protected
  ShapeGradient? dco_decode_opt_box_autoadd_shape_gradient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_shape_gradient(raw);
  }

  @protected
  ShapeShadow? dco_decode_opt_box_autoadd_shape_shadow(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_shape_shadow(raw);
  }

  @protected
  RenderShape dco_decode_render_shape(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return RenderShape(
      id: dco_decode_String(arr[0]),
      shapeType: dco_decode_shape_type(arr[1]),
      transform: dco_decode_matrix_2_d(arr[2]),
      parentId: dco_decode_opt_String(arr[3]),
      frameId: dco_decode_opt_String(arr[4]),
      sortOrder: dco_decode_i_32(arr[5]),
      opacity: dco_decode_f_64(arr[6]),
      hidden: dco_decode_bool(arr[7]),
      rotation: dco_decode_f_64(arr[8]),
      fills: dco_decode_list_shape_fill(arr[9]),
      strokes: dco_decode_list_shape_stroke(arr[10]),
      shadow: dco_decode_opt_box_autoadd_shape_shadow(arr[11]),
      blur: dco_decode_opt_box_autoadd_shape_blur(arr[12]),
      geometry: dco_decode_shape_geometry(arr[13]),
    );
  }

  @protected
  ShadowStyle dco_decode_shadow_style(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ShadowStyle.values[raw as int];
  }

  @protected
  ShapeBlur dco_decode_shape_blur(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ShapeBlur(
      blurType: dco_decode_blur_type(arr[0]),
      value: dco_decode_f_64(arr[1]),
      hidden: dco_decode_bool(arr[2]),
    );
  }

  @protected
  ShapeFill dco_decode_shape_fill(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ShapeFill(
      color: dco_decode_u_32(arr[0]),
      opacity: dco_decode_f_64(arr[1]),
      hidden: dco_decode_bool(arr[2]),
      gradient: dco_decode_opt_box_autoadd_shape_gradient(arr[3]),
    );
  }

  @protected
  ShapeGeometry dco_decode_shape_geometry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ShapeGeometry_Rectangle(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
          r1: dco_decode_f_64(raw[3]),
          r2: dco_decode_f_64(raw[4]),
          r3: dco_decode_f_64(raw[5]),
          r4: dco_decode_f_64(raw[6]),
        );
      case 1:
        return ShapeGeometry_Ellipse(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
        );
      case 2:
        return ShapeGeometry_Text(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
          text: dco_decode_String(raw[3]),
          fontSize: dco_decode_f_64(raw[4]),
          fontFamily: dco_decode_String(raw[5]),
          fontWeight: dco_decode_u_16(raw[6]),
          lineHeight: dco_decode_f_64(raw[7]),
          letterSpacingPercent: dco_decode_f_64(raw[8]),
          textAlign: dco_decode_text_align(raw[9]),
        );
      case 3:
        return ShapeGeometry_Frame(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
          clipContent: dco_decode_bool(raw[3]),
        );
      case 4:
        return ShapeGeometry_Group(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
        );
      case 5:
        return ShapeGeometry_Path(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
          pathData: dco_decode_String(raw[3]),
          closed: dco_decode_bool(raw[4]),
        );
      case 6:
        return ShapeGeometry_Image(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
          assetId: dco_decode_String(raw[3]),
        );
      case 7:
        return ShapeGeometry_Svg(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
          svgContent: dco_decode_String(raw[3]),
        );
      case 8:
        return ShapeGeometry_Bool(
          width: dco_decode_f_64(raw[1]),
          height: dco_decode_f_64(raw[2]),
          operation: dco_decode_bool_op(raw[3]),
        );
      default:
        throw Exception('unreachable');
    }
  }

  @protected
  ShapeGradient dco_decode_shape_gradient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ShapeGradient(
      gradientType: dco_decode_gradient_type(arr[0]),
      stops: dco_decode_list_gradient_stop(arr[1]),
      startX: dco_decode_f_64(arr[2]),
      startY: dco_decode_f_64(arr[3]),
      endX: dco_decode_f_64(arr[4]),
      endY: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  ShapeShadow dco_decode_shape_shadow(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ShapeShadow(
      style: dco_decode_shadow_style(arr[0]),
      color: dco_decode_u_32(arr[1]),
      opacity: dco_decode_f_64(arr[2]),
      offsetX: dco_decode_f_64(arr[3]),
      offsetY: dco_decode_f_64(arr[4]),
      blur: dco_decode_f_64(arr[5]),
      spread: dco_decode_f_64(arr[6]),
      hidden: dco_decode_bool(arr[7]),
    );
  }

  @protected
  ShapeStroke dco_decode_shape_stroke(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ShapeStroke(
      color: dco_decode_u_32(arr[0]),
      width: dco_decode_f_64(arr[1]),
      opacity: dco_decode_f_64(arr[2]),
      hidden: dco_decode_bool(arr[3]),
      alignment: dco_decode_stroke_alignment(arr[4]),
      cap: dco_decode_stroke_cap(arr[5]),
      join: dco_decode_stroke_join(arr[6]),
    );
  }

  @protected
  ShapeType dco_decode_shape_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ShapeType.values[raw as int];
  }

  @protected
  StrokeAlignment dco_decode_stroke_alignment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StrokeAlignment.values[raw as int];
  }

  @protected
  StrokeCap dco_decode_stroke_cap(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StrokeCap.values[raw as int];
  }

  @protected
  StrokeJoin dco_decode_stroke_join(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StrokeJoin.values[raw as int];
  }

  @protected
  TextAlign dco_decode_text_align(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TextAlign.values[raw as int];
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  CanvasEngine
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CanvasEngine
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CanvasEngine
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  CanvasEngine
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CanvasEngineImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlurType sse_decode_blur_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return BlurType.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BoolOp sse_decode_bool_op(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return BoolOp.values[inner];
  }

  @protected
  ShapeBlur sse_decode_box_autoadd_shape_blur(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_shape_blur(deserializer);
  }

  @protected
  ShapeGradient sse_decode_box_autoadd_shape_gradient(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_shape_gradient(deserializer);
  }

  @protected
  ShapeShadow sse_decode_box_autoadd_shape_shadow(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_shape_shadow(deserializer);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GradientStop sse_decode_gradient_stop(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_offset = sse_decode_f_64(deserializer);
    final var_color = sse_decode_u_32(deserializer);
    return GradientStop(offset: var_offset, color: var_color);
  }

  @protected
  GradientType sse_decode_gradient_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return GradientType.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<GradientStop> sse_decode_list_gradient_stop(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <GradientStop>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_gradient_stop(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RenderShape> sse_decode_list_render_shape(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <RenderShape>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_render_shape(deserializer));
    }
    return ans_;
  }

  @protected
  List<ShapeFill> sse_decode_list_shape_fill(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <ShapeFill>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_shape_fill(deserializer));
    }
    return ans_;
  }

  @protected
  List<ShapeStroke> sse_decode_list_shape_stroke(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final len_ = sse_decode_i_32(deserializer);
    final ans_ = <ShapeStroke>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_shape_stroke(deserializer));
    }
    return ans_;
  }

  @protected
  Matrix2D sse_decode_matrix_2_d(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_a = sse_decode_f_64(deserializer);
    final var_b = sse_decode_f_64(deserializer);
    final var_c = sse_decode_f_64(deserializer);
    final var_d = sse_decode_f_64(deserializer);
    final var_e = sse_decode_f_64(deserializer);
    final var_f = sse_decode_f_64(deserializer);
    return Matrix2D(a: var_a, b: var_b, c: var_c, d: var_d, e: var_e, f: var_f);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_String(deserializer);
    } else {
      return null;
    }
  }

  @protected
  ShapeBlur? sse_decode_opt_box_autoadd_shape_blur(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_shape_blur(deserializer);
    } else {
      return null;
    }
  }

  @protected
  ShapeGradient? sse_decode_opt_box_autoadd_shape_gradient(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_shape_gradient(deserializer);
    } else {
      return null;
    }
  }

  @protected
  ShapeShadow? sse_decode_opt_box_autoadd_shape_shadow(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_shape_shadow(deserializer);
    } else {
      return null;
    }
  }

  @protected
  RenderShape sse_decode_render_shape(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_id = sse_decode_String(deserializer);
    final var_shapeType = sse_decode_shape_type(deserializer);
    final var_transform = sse_decode_matrix_2_d(deserializer);
    final var_parentId = sse_decode_opt_String(deserializer);
    final var_frameId = sse_decode_opt_String(deserializer);
    final var_sortOrder = sse_decode_i_32(deserializer);
    final var_opacity = sse_decode_f_64(deserializer);
    final var_hidden = sse_decode_bool(deserializer);
    final var_rotation = sse_decode_f_64(deserializer);
    final var_fills = sse_decode_list_shape_fill(deserializer);
    final var_strokes = sse_decode_list_shape_stroke(deserializer);
    final var_shadow = sse_decode_opt_box_autoadd_shape_shadow(deserializer);
    final var_blur = sse_decode_opt_box_autoadd_shape_blur(deserializer);
    final var_geometry = sse_decode_shape_geometry(deserializer);
    return RenderShape(
        id: var_id,
        shapeType: var_shapeType,
        transform: var_transform,
        parentId: var_parentId,
        frameId: var_frameId,
        sortOrder: var_sortOrder,
        opacity: var_opacity,
        hidden: var_hidden,
        rotation: var_rotation,
        fills: var_fills,
        strokes: var_strokes,
        shadow: var_shadow,
        blur: var_blur,
        geometry: var_geometry);
  }

  @protected
  ShadowStyle sse_decode_shadow_style(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return ShadowStyle.values[inner];
  }

  @protected
  ShapeBlur sse_decode_shape_blur(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_blurType = sse_decode_blur_type(deserializer);
    final var_value = sse_decode_f_64(deserializer);
    final var_hidden = sse_decode_bool(deserializer);
    return ShapeBlur(
        blurType: var_blurType, value: var_value, hidden: var_hidden);
  }

  @protected
  ShapeFill sse_decode_shape_fill(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_color = sse_decode_u_32(deserializer);
    final var_opacity = sse_decode_f_64(deserializer);
    final var_hidden = sse_decode_bool(deserializer);
    final var_gradient =
        sse_decode_opt_box_autoadd_shape_gradient(deserializer);
    return ShapeFill(
        color: var_color,
        opacity: var_opacity,
        hidden: var_hidden,
        gradient: var_gradient);
  }

  @protected
  ShapeGeometry sse_decode_shape_geometry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        final var_r1 = sse_decode_f_64(deserializer);
        final var_r2 = sse_decode_f_64(deserializer);
        final var_r3 = sse_decode_f_64(deserializer);
        final var_r4 = sse_decode_f_64(deserializer);
        return ShapeGeometry_Rectangle(
            width: var_width,
            height: var_height,
            r1: var_r1,
            r2: var_r2,
            r3: var_r3,
            r4: var_r4);
      case 1:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        return ShapeGeometry_Ellipse(width: var_width, height: var_height);
      case 2:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        final var_text = sse_decode_String(deserializer);
        final var_fontSize = sse_decode_f_64(deserializer);
        final var_fontFamily = sse_decode_String(deserializer);
        final var_fontWeight = sse_decode_u_16(deserializer);
        final var_lineHeight = sse_decode_f_64(deserializer);
        final var_letterSpacingPercent = sse_decode_f_64(deserializer);
        final var_textAlign = sse_decode_text_align(deserializer);
        return ShapeGeometry_Text(
            width: var_width,
            height: var_height,
            text: var_text,
            fontSize: var_fontSize,
            fontFamily: var_fontFamily,
            fontWeight: var_fontWeight,
            lineHeight: var_lineHeight,
            letterSpacingPercent: var_letterSpacingPercent,
            textAlign: var_textAlign);
      case 3:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        final var_clipContent = sse_decode_bool(deserializer);
        return ShapeGeometry_Frame(
            width: var_width, height: var_height, clipContent: var_clipContent);
      case 4:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        return ShapeGeometry_Group(width: var_width, height: var_height);
      case 5:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        final var_pathData = sse_decode_String(deserializer);
        final var_closed = sse_decode_bool(deserializer);
        return ShapeGeometry_Path(
            width: var_width,
            height: var_height,
            pathData: var_pathData,
            closed: var_closed);
      case 6:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        final var_assetId = sse_decode_String(deserializer);
        return ShapeGeometry_Image(
            width: var_width, height: var_height, assetId: var_assetId);
      case 7:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        final var_svgContent = sse_decode_String(deserializer);
        return ShapeGeometry_Svg(
            width: var_width, height: var_height, svgContent: var_svgContent);
      case 8:
        final var_width = sse_decode_f_64(deserializer);
        final var_height = sse_decode_f_64(deserializer);
        final var_operation = sse_decode_bool_op(deserializer);
        return ShapeGeometry_Bool(
            width: var_width, height: var_height, operation: var_operation);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ShapeGradient sse_decode_shape_gradient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_gradientType = sse_decode_gradient_type(deserializer);
    final var_stops = sse_decode_list_gradient_stop(deserializer);
    final var_startX = sse_decode_f_64(deserializer);
    final var_startY = sse_decode_f_64(deserializer);
    final var_endX = sse_decode_f_64(deserializer);
    final var_endY = sse_decode_f_64(deserializer);
    return ShapeGradient(
        gradientType: var_gradientType,
        stops: var_stops,
        startX: var_startX,
        startY: var_startY,
        endX: var_endX,
        endY: var_endY);
  }

  @protected
  ShapeShadow sse_decode_shape_shadow(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_style = sse_decode_shadow_style(deserializer);
    final var_color = sse_decode_u_32(deserializer);
    final var_opacity = sse_decode_f_64(deserializer);
    final var_offsetX = sse_decode_f_64(deserializer);
    final var_offsetY = sse_decode_f_64(deserializer);
    final var_blur = sse_decode_f_64(deserializer);
    final var_spread = sse_decode_f_64(deserializer);
    final var_hidden = sse_decode_bool(deserializer);
    return ShapeShadow(
        style: var_style,
        color: var_color,
        opacity: var_opacity,
        offsetX: var_offsetX,
        offsetY: var_offsetY,
        blur: var_blur,
        spread: var_spread,
        hidden: var_hidden);
  }

  @protected
  ShapeStroke sse_decode_shape_stroke(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_color = sse_decode_u_32(deserializer);
    final var_width = sse_decode_f_64(deserializer);
    final var_opacity = sse_decode_f_64(deserializer);
    final var_hidden = sse_decode_bool(deserializer);
    final var_alignment = sse_decode_stroke_alignment(deserializer);
    final var_cap = sse_decode_stroke_cap(deserializer);
    final var_join = sse_decode_stroke_join(deserializer);
    return ShapeStroke(
        color: var_color,
        width: var_width,
        opacity: var_opacity,
        hidden: var_hidden,
        alignment: var_alignment,
        cap: var_cap,
        join: var_join);
  }

  @protected
  ShapeType sse_decode_shape_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return ShapeType.values[inner];
  }

  @protected
  StrokeAlignment sse_decode_stroke_alignment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return StrokeAlignment.values[inner];
  }

  @protected
  StrokeCap sse_decode_stroke_cap(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return StrokeCap.values[inner];
  }

  @protected
  StrokeJoin sse_decode_stroke_join(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return StrokeJoin.values[inner];
  }

  @protected
  TextAlign sse_decode_text_align(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_i_32(deserializer);
    return TextAlign.values[inner];
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CanvasEngineImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CanvasEngineImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CanvasEngineImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCanvasEngine(
          CanvasEngine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as CanvasEngineImpl).frbInternalSseEncode(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_blur_type(BlurType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bool_op(BoolOp self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_box_autoadd_shape_blur(
      ShapeBlur self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shape_blur(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_shape_gradient(
      ShapeGradient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shape_gradient(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_shape_shadow(
      ShapeShadow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shape_shadow(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_gradient_stop(GradientStop self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.offset, serializer);
    sse_encode_u_32(self.color, serializer);
  }

  @protected
  void sse_encode_gradient_type(GradientType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_gradient_stop(
      List<GradientStop> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_gradient_stop(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_render_shape(
      List<RenderShape> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_render_shape(item, serializer);
    }
  }

  @protected
  void sse_encode_list_shape_fill(
      List<ShapeFill> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_shape_fill(item, serializer);
    }
  }

  @protected
  void sse_encode_list_shape_stroke(
      List<ShapeStroke> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_shape_stroke(item, serializer);
    }
  }

  @protected
  void sse_encode_matrix_2_d(Matrix2D self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.a, serializer);
    sse_encode_f_64(self.b, serializer);
    sse_encode_f_64(self.c, serializer);
    sse_encode_f_64(self.d, serializer);
    sse_encode_f_64(self.e, serializer);
    sse_encode_f_64(self.f, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_shape_blur(
      ShapeBlur? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_shape_blur(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_shape_gradient(
      ShapeGradient? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_shape_gradient(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_shape_shadow(
      ShapeShadow? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_shape_shadow(self, serializer);
    }
  }

  @protected
  void sse_encode_render_shape(RenderShape self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_shape_type(self.shapeType, serializer);
    sse_encode_matrix_2_d(self.transform, serializer);
    sse_encode_opt_String(self.parentId, serializer);
    sse_encode_opt_String(self.frameId, serializer);
    sse_encode_i_32(self.sortOrder, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_bool(self.hidden, serializer);
    sse_encode_f_64(self.rotation, serializer);
    sse_encode_list_shape_fill(self.fills, serializer);
    sse_encode_list_shape_stroke(self.strokes, serializer);
    sse_encode_opt_box_autoadd_shape_shadow(self.shadow, serializer);
    sse_encode_opt_box_autoadd_shape_blur(self.blur, serializer);
    sse_encode_shape_geometry(self.geometry, serializer);
  }

  @protected
  void sse_encode_shadow_style(ShadowStyle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_shape_blur(ShapeBlur self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_blur_type(self.blurType, serializer);
    sse_encode_f_64(self.value, serializer);
    sse_encode_bool(self.hidden, serializer);
  }

  @protected
  void sse_encode_shape_fill(ShapeFill self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.color, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_bool(self.hidden, serializer);
    sse_encode_opt_box_autoadd_shape_gradient(self.gradient, serializer);
  }

  @protected
  void sse_encode_shape_geometry(ShapeGeometry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ShapeGeometry_Rectangle(
          width: final width,
          height: final height,
          r1: final r1,
          r2: final r2,
          r3: final r3,
          r4: final r4
        ):
        sse_encode_i_32(0, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_f_64(r1, serializer);
        sse_encode_f_64(r2, serializer);
        sse_encode_f_64(r3, serializer);
        sse_encode_f_64(r4, serializer);
      case ShapeGeometry_Ellipse(width: final width, height: final height):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
      case ShapeGeometry_Text(
          width: final width,
          height: final height,
          text: final text,
          fontSize: final fontSize,
          fontFamily: final fontFamily,
          fontWeight: final fontWeight,
          lineHeight: final lineHeight,
          letterSpacingPercent: final letterSpacingPercent,
          textAlign: final textAlign
        ):
        sse_encode_i_32(2, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_String(text, serializer);
        sse_encode_f_64(fontSize, serializer);
        sse_encode_String(fontFamily, serializer);
        sse_encode_u_16(fontWeight, serializer);
        sse_encode_f_64(lineHeight, serializer);
        sse_encode_f_64(letterSpacingPercent, serializer);
        sse_encode_text_align(textAlign, serializer);
      case ShapeGeometry_Frame(
          width: final width,
          height: final height,
          clipContent: final clipContent
        ):
        sse_encode_i_32(3, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_bool(clipContent, serializer);
      case ShapeGeometry_Group(width: final width, height: final height):
        sse_encode_i_32(4, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
      case ShapeGeometry_Path(
          width: final width,
          height: final height,
          pathData: final pathData,
          closed: final closed
        ):
        sse_encode_i_32(5, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_String(pathData, serializer);
        sse_encode_bool(closed, serializer);
      case ShapeGeometry_Image(
          width: final width,
          height: final height,
          assetId: final assetId
        ):
        sse_encode_i_32(6, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_String(assetId, serializer);
      case ShapeGeometry_Svg(
          width: final width,
          height: final height,
          svgContent: final svgContent
        ):
        sse_encode_i_32(7, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_String(svgContent, serializer);
      case ShapeGeometry_Bool(
          width: final width,
          height: final height,
          operation: final operation
        ):
        sse_encode_i_32(8, serializer);
        sse_encode_f_64(width, serializer);
        sse_encode_f_64(height, serializer);
        sse_encode_bool_op(operation, serializer);
    }
  }

  @protected
  void sse_encode_shape_gradient(ShapeGradient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gradient_type(self.gradientType, serializer);
    sse_encode_list_gradient_stop(self.stops, serializer);
    sse_encode_f_64(self.startX, serializer);
    sse_encode_f_64(self.startY, serializer);
    sse_encode_f_64(self.endX, serializer);
    sse_encode_f_64(self.endY, serializer);
  }

  @protected
  void sse_encode_shape_shadow(ShapeShadow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shadow_style(self.style, serializer);
    sse_encode_u_32(self.color, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_f_64(self.offsetX, serializer);
    sse_encode_f_64(self.offsetY, serializer);
    sse_encode_f_64(self.blur, serializer);
    sse_encode_f_64(self.spread, serializer);
    sse_encode_bool(self.hidden, serializer);
  }

  @protected
  void sse_encode_shape_stroke(ShapeStroke self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.color, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_bool(self.hidden, serializer);
    sse_encode_stroke_alignment(self.alignment, serializer);
    sse_encode_stroke_cap(self.cap, serializer);
    sse_encode_stroke_join(self.join, serializer);
  }

  @protected
  void sse_encode_shape_type(ShapeType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_stroke_alignment(
      StrokeAlignment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_stroke_cap(StrokeCap self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_stroke_join(StrokeJoin self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_text_align(TextAlign self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CanvasEngineImpl extends RustOpaque implements CanvasEngine {
  // Not to be used by end users
  CanvasEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CanvasEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CanvasEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CanvasEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CanvasEnginePtr,
  );

  /// Hit test: find all shape IDs at a point (in canvas coordinates).
  /// Returns IDs sorted by z-order (topmost first).
  List<String> hitTestPoint({required double x, required double y}) =>
      RustLib.instance.api
          .crateApiEngineCanvasEngineHitTestPoint(that: this, x: x, y: y);

  /// Hit test: find all shape IDs overlapping a rectangle (for drag-select).
  List<String> hitTestRect(
          {required double x,
          required double y,
          required double w,
          required double h}) =>
      RustLib.instance.api.crateApiEngineCanvasEngineHitTestRect(
          that: this, x: x, y: y, w: w, h: h);

  /// Bulk-load all shapes (full sync). Replaces the entire scene.
  Future<void> loadAllShapes({required List<RenderShape> shapes}) =>
      RustLib.instance.api
          .crateApiEngineCanvasEngineLoadAllShapes(that: this, shapes: shapes);

  /// Get depth-first shape IDs in paint order.
  List<String> paintOrder() =>
      RustLib.instance.api.crateApiEngineCanvasEnginePaintOrder(
        that: this,
      );

  /// Query shape IDs visible within a viewport rectangle.
  List<String> queryVisible(
          {required double viewportMinX,
          required double viewportMinY,
          required double viewportMaxX,
          required double viewportMaxY}) =>
      RustLib.instance.api.crateApiEngineCanvasEngineQueryVisible(
          that: this,
          viewportMinX: viewportMinX,
          viewportMinY: viewportMinY,
          viewportMaxX: viewportMaxX,
          viewportMaxY: viewportMaxY);

  /// Get shape count.
  BigInt shapeCount() =>
      RustLib.instance.api.crateApiEngineCanvasEngineShapeCount(
        that: this,
      );

  /// Sync a batch of shape changes from Dart → Rust.
  /// Called when CanvasBloc emits a new state.
  Future<void> syncShapes(
          {required List<RenderShape> added,
          required List<RenderShape> updated,
          required List<String> removed}) =>
      RustLib.instance.api.crateApiEngineCanvasEngineSyncShapes(
          that: this, added: added, updated: updated, removed: removed);
}
