// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../frb_generated.dart';
import '../math/matrix2d.dart';

part 'shape.freezed.dart';

/// Blur type.
enum BlurType {
  layer,
  background,
  ;
}

/// Boolean operation type.
enum BoolOp {
  union,
  subtract,
  intersect,
  exclude,
  ;
}

/// A gradient stop (offset + color).
class GradientStop {
  final double offset;
  final int color;

  const GradientStop({
    required this.offset,
    required this.color,
  });

  @override
  int get hashCode => offset.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GradientStop &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          color == other.color;
}

/// Gradient type.
enum GradientType {
  linear,
  radial,
  ;
}

/// A render-optimized shape. Mirrors the Dart `Shape` hierarchy but only
/// carries fields needed for rendering and spatial queries.
class RenderShape {
  final String id;
  final ShapeType shapeType;
  final Matrix2D transform;
  final String? parentId;
  final String? frameId;
  final int sortOrder;
  final double opacity;
  final bool hidden;
  final double rotation;
  final List<ShapeFill> fills;
  final List<ShapeStroke> strokes;
  final ShapeShadow? shadow;
  final ShapeBlur? blur;
  final ShapeGeometry geometry;

  const RenderShape({
    required this.id,
    required this.shapeType,
    required this.transform,
    required this.sortOrder,
    required this.opacity,
    required this.hidden,
    required this.rotation,
    required this.fills,
    required this.strokes,
    required this.geometry,
    this.parentId,
    this.frameId,
    this.shadow,
    this.blur,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      shapeType.hashCode ^
      transform.hashCode ^
      parentId.hashCode ^
      frameId.hashCode ^
      sortOrder.hashCode ^
      opacity.hashCode ^
      hidden.hashCode ^
      rotation.hashCode ^
      fills.hashCode ^
      strokes.hashCode ^
      shadow.hashCode ^
      blur.hashCode ^
      geometry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderShape &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          shapeType == other.shapeType &&
          transform == other.transform &&
          parentId == other.parentId &&
          frameId == other.frameId &&
          sortOrder == other.sortOrder &&
          opacity == other.opacity &&
          hidden == other.hidden &&
          rotation == other.rotation &&
          fills == other.fills &&
          strokes == other.strokes &&
          shadow == other.shadow &&
          blur == other.blur &&
          geometry == other.geometry;
}

/// Shadow style.
enum ShadowStyle {
  drop,
  inner,
  ;
}

/// Blur effect.
class ShapeBlur {
  final BlurType blurType;
  final double value;
  final bool hidden;

  const ShapeBlur({
    required this.blurType,
    required this.value,
    required this.hidden,
  });

  @override
  int get hashCode => blurType.hashCode ^ value.hashCode ^ hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeBlur &&
          runtimeType == other.runtimeType &&
          blurType == other.blurType &&
          value == other.value &&
          hidden == other.hidden;
}

/// A single fill layer.
class ShapeFill {
  final int color;
  final double opacity;
  final bool hidden;
  final ShapeGradient? gradient;

  const ShapeFill({
    required this.color,
    required this.opacity,
    required this.hidden,
    this.gradient,
  });

  @override
  int get hashCode =>
      color.hashCode ^ opacity.hashCode ^ hidden.hashCode ^ gradient.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeFill &&
          runtimeType == other.runtimeType &&
          color == other.color &&
          opacity == other.opacity &&
          hidden == other.hidden &&
          gradient == other.gradient;
}

@freezed
sealed class ShapeGeometry with _$ShapeGeometry {
  const ShapeGeometry._();

  const factory ShapeGeometry.rectangle({
    required double width,
    required double height,
    required double r1,
    required double r2,
    required double r3,
    required double r4,
  }) = ShapeGeometry_Rectangle;
  const factory ShapeGeometry.ellipse({
    required double width,
    required double height,
  }) = ShapeGeometry_Ellipse;
  const factory ShapeGeometry.text({
    required double width,
    required double height,
    required String text,
    required double fontSize,
    required String fontFamily,
    required int fontWeight,
    required double lineHeight,
    required double letterSpacingPercent,
    required TextAlign textAlign,
  }) = ShapeGeometry_Text;
  const factory ShapeGeometry.frame({
    required double width,
    required double height,
    required bool clipContent,
  }) = ShapeGeometry_Frame;
  const factory ShapeGeometry.group({
    required double width,
    required double height,
  }) = ShapeGeometry_Group;
  const factory ShapeGeometry.path({
    required double width,
    required double height,
    required String pathData,
    required bool closed,
  }) = ShapeGeometry_Path;
  const factory ShapeGeometry.image({
    required double width,
    required double height,
    required String assetId,
  }) = ShapeGeometry_Image;
  const factory ShapeGeometry.svg({
    required double width,
    required double height,
    required String svgContent,
  }) = ShapeGeometry_Svg;
  const factory ShapeGeometry.bool({
    required double width,
    required double height,
    required BoolOp operation,
  }) = ShapeGeometry_Bool;
}

/// Gradient definition.
class ShapeGradient {
  final GradientType gradientType;
  final List<GradientStop> stops;
  final double startX;
  final double startY;
  final double endX;
  final double endY;

  const ShapeGradient({
    required this.gradientType,
    required this.stops,
    required this.startX,
    required this.startY,
    required this.endX,
    required this.endY,
  });

  @override
  int get hashCode =>
      gradientType.hashCode ^
      stops.hashCode ^
      startX.hashCode ^
      startY.hashCode ^
      endX.hashCode ^
      endY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeGradient &&
          runtimeType == other.runtimeType &&
          gradientType == other.gradientType &&
          stops == other.stops &&
          startX == other.startX &&
          startY == other.startY &&
          endX == other.endX &&
          endY == other.endY;
}

/// Shadow effect.
class ShapeShadow {
  final ShadowStyle style;
  final int color;
  final double opacity;
  final double offsetX;
  final double offsetY;
  final double blur;
  final double spread;
  final bool hidden;

  const ShapeShadow({
    required this.style,
    required this.color,
    required this.opacity,
    required this.offsetX,
    required this.offsetY,
    required this.blur,
    required this.spread,
    required this.hidden,
  });

  @override
  int get hashCode =>
      style.hashCode ^
      color.hashCode ^
      opacity.hashCode ^
      offsetX.hashCode ^
      offsetY.hashCode ^
      blur.hashCode ^
      spread.hashCode ^
      hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeShadow &&
          runtimeType == other.runtimeType &&
          style == other.style &&
          color == other.color &&
          opacity == other.opacity &&
          offsetX == other.offsetX &&
          offsetY == other.offsetY &&
          blur == other.blur &&
          spread == other.spread &&
          hidden == other.hidden;
}

/// A single stroke layer.
class ShapeStroke {
  final int color;
  final double width;
  final double opacity;
  final bool hidden;
  final StrokeAlignment alignment;
  final StrokeCap cap;
  final StrokeJoin join;

  const ShapeStroke({
    required this.color,
    required this.width,
    required this.opacity,
    required this.hidden,
    required this.alignment,
    required this.cap,
    required this.join,
  });

  @override
  int get hashCode =>
      color.hashCode ^
      width.hashCode ^
      opacity.hashCode ^
      hidden.hashCode ^
      alignment.hashCode ^
      cap.hashCode ^
      join.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeStroke &&
          runtimeType == other.runtimeType &&
          color == other.color &&
          width == other.width &&
          opacity == other.opacity &&
          hidden == other.hidden &&
          alignment == other.alignment &&
          cap == other.cap &&
          join == other.join;
}

/// Mirrors the Dart `ShapeType` enum from packages/core.
enum ShapeType {
  rectangle,
  ellipse,
  text,
  frame,
  group,
  path,
  image,
  svg,
  bool,
  ;
}

/// Stroke alignment relative to path.
enum StrokeAlignment {
  center,
  inside,
  outside,
  ;
}

/// Stroke cap.
enum StrokeCap {
  butt,
  round,
  square,
  ;
}

/// Stroke join.
enum StrokeJoin {
  miter,
  round,
  bevel,
  ;
}

/// Text alignment, mirrors Dart's `TextAlign`.
enum TextAlign {
  left,
  center,
  right,
  justify,
  ;
}
